FROM node:12.13.1-alpine as node

RUN \
  apk add --no-cache git && \
  npm install -g @angular/cli@^9.1.0 && \
  npm install -g @angular/compiler-cli@^9.1.0

COPY entrypoint.sh /entrypoint.sh

WORKDIR /otto
EXPOSE 4200
ENTRYPOINT ["/entrypoint.sh"]
